title: "슬픈 안드로이드"
description: "우리 앞에 있는 모든 시련들 겁낼 필요 없다"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.jpg"

# Social Links
email: "tnwlsgk1002@gmail.com"
github_username: "tnwlsgk1002"
# twitter_username: "twitter"
# instagram_username: "instagram"
linkedin_username: "수진-이-35bb57207"
# facebook_username: "facebook"

# External API
data-repo: "tnwlsgk1002/tnwlsgk1002.github.io"
data-repo-id: "R_kgDONT9Ftw"
data-category: "Q&A"
data-category-id: "DIC_kwDONT9Ft84Ckjpo"
goatcounter_code: "tnwlsgk1002githubioblog"
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator
kramdown:
  input: GFM
  hard_wrap: true
